version: '3.8'
services:
  keycloak_web:
    build:
      context: .
      dockerfile: keycloak_dockerfile/Dockerfile
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/realm-export.json:/tmp/realm-export.json
      - ./import-client-scope.sh:/opt/keycloak/import-client-scope.sh
    entrypoint: [ "/bin/sh", "-c", "/opt/keycloak/bin/kc.sh start-dev --import-realm -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/tmp/realm-export.json && sh /opt/keycloak/import-client-scope.sh" ]
    ports:
      - '8080:8080'
  app:
    build:
      context: .
      dockerfile: app_dockerfile/Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - 'keycloak_web'